// Generated by https://quicktype.io

export interface ProfileResponse {
  id: number;
  age: number;
  gender: number;
  weight: number;
  targetWeight: number;
  height: number;
  isVeg: boolean;
  userId: number;
  activityLevel: number;
  goal: number;
  pace: number;
}
